### PR TITLE
Delete repo when Borgmatic fail

### PR DESCRIPTION
**Pull request by florentk**
relation with #32

### CODE REVIEW

**Comment by kelson42** [comment]
@florentk Is this PR over? ready to review?

**Comment by kelson42** [comment]
Does it fix #32?

**Comment by florentk** [comment]
> Does it fix #32? Is that ticket ready to review? If not, please put PR in draft to avoid confusion.

#32 is not clear, then I don't no if this PR fix it

**Comment by rgaudin** [comment]
As explained in #32, we don't want to delete the repo.

**Pull request closed without merging**
