### PR TITLE
BB credential in BW, external tool to setup, improve stdout and README

### LINKED ISSUE #2: Don't require master bitwarden password
Current implementation requires the master credentials of the bitwarden account for every backup.

We need to separate the *sub-account*/*token* creation process so that the backup is launched using limited credentials

### PR DESCRIPTION
**Pull request by florentk**
resolve #2 #10 #13 #14 #5

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
@florentk, this is very difficult to review. there are many changes and several commit after the review request… Instructions on how to test are missing or not clear.

Also, this is just not working. It's not possible to setup the repo as `init_config` is called before that script…

Please, fix just this single problem and don't add any other feature to this so we can merge it.

I am about to open a number of new issues. Let's merge this in first and then, please submit one PR per ticket or a limited number of related tickets so we can review and merge easily.

**Comment by florentk** [comment]
> 
> Also, this is just not working. It's not possible to setup the repo as `init_config` is called before that script…
> 
@rgaudin I not understand, I work for me when I run

```
docker run -e BORGBASE_NAME=test_borg \
           -e BORGBASE_KEY=<borgbase_api_token> \
       kiwix/borg-backup setup-new-repo
```

`init_config` is called, but if `test_borg` not exit in BitWarden,  `setup-new-repo` is called. Otherwise I dont see under when to call it.

**Comment by florentk** [comment]
@rgaudin I have clearly separate the command `backup` and `setup-new-repo`, is maybe better now ?

**Comment by rgaudin** [comment]
Thank you, it's better now but still (using `BORGBASE_NAME=test-1`)

```
You are not logged in.
? Email address: reg+backupmaster2@kiwix.org
? Master password: [hidden]
Generate SSH key ...
rm: cannot remove '/root/.ssh/test-1_id*': No such file or directory
Generating public/private ed25519 key pair.
Your identification has been saved in /root/.ssh/test-1_id.
Your public key has been saved in /root/.ssh/test-1_id.pub.
The key fingerprint is:
SHA256:5S2X5LhPKBuiXtLFU/dpx70xJMb+gm1eVCWNIfvwOqg backup@test-1
The key's randomart image is:
+--[ED25519 256]--+
|            . o+.|
|            .o..o|
|          o =+ ..|
|       . + *o*ooo|
|        S + =.*++|
|     . . . *ooo.+|
|    . + o +.++ + |
|     + . = oo.o  |
|   .o   E   ..   |
+----[SHA256]-----+
Save key to BitWarden
c9f386a8-febd-46f4-9cb6-ac4100a8339e Kiwix Backup (reg)
To share with a organization, please enter it id (leave blank for no share) : c9f386a8-febd-46f4-9cb6-ac4100a8339e
f889465c-f322-4768-9665-ac4100a833a3 Default Collection
Please enter a collection id : f889465c-f322-4768-9665-ac4100a833a3
Share key ...
Repo not exists with name test-1 , create it ...
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
Use repo path : q20343f1@box-eu8.borgbase.com:repo
Init Borgmatic ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository
Remote: Warning: Permanently added the ECDSA host key for IP address '95.217.115.47' to the list of known hosts.
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
```

**Comment by kelson42** [comment]
Small remark, in English there is no space before “:” character.

**Comment by florentk** [comment]
@rgaudin  yes, I have frequently this error, but even if this error happen, the setup is correct. I added the sleep to avoid this, but that's no enough. I see what I can do.

**Comment by rgaudin** [comment]
OK then please open a ticket about that so we don't forget to fix it

**Comment by rgaudin** [comment]
btw I've tried with 30s sleep and still get the same error so I'm not convinced it's the only failing cause

**Comment by florentk** [comment]
> btw I've tried with 30s sleep and still get the same error so I'm not convinced it's the only failing cause
@rgaudin 
I've move the sleep and I retry five time before stop the setup, and this seem works now

**Review by rgaudin — CHANGES_REQUESTED** [review]
Still not working…

When using a previously attempted name (`test-1`):

```sh
docker build . -t borg-backup && docker run -v $HOME/data/to-backup/A:/storage/volA:ro -v $HOME/data/to-backup/B:/storage/volB:ro -e BORGBASE_NAME=test-1 -e BORGBASE_KEY=replaced -it borg-backup setup-new-repo
```

```
? Email address: reg+backupmaster2@kiwix.org
? Master password: [hidden]
Generate SSH key ...
Generating public/private ed25519 key pair.
Your identification has been saved in /root/.ssh/test-1_id.
Your public key has been saved in /root/.ssh/test-1_id.pub.
The key fingerprint is:
SHA256:dcQbr3mCh7oXKo1o84wO32vQaksRPS+3BWTI+8NYKUE backup@test-1
The key's randomart image is:
+--[ED25519 256]--+
|     oE.o  ..    |
|     .+o   .o    |
|    . oo... .+   |
|     .oooo .. .  |
|    ...*S .o o   |
|    ..oo+o+ = .  |
|  . .+ o.+ o o   |
|   +*++ + .      |
|   +===o.o       |
+----[SHA256]-----+
Save key to BitWarden
c9f386a8-febd-46f4-9cb6-ac4100a8339e Kiwix Backup (reg)
To share with a organization, please enter it id (leave blank for no share):c9f386a8-febd-46f4-9cb6-ac4100a8339e
f889465c-f322-4768-9665-ac4100a833a3 Default Collection
Please enter a collection id: f889465c-f322-4768-9665-ac4100a833a3
Share key ...
Repo exists with name test-1
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
# box-eu8.borgbase.com:22 SSH-2.0-OpenSSH_8.0
Use repo path : q20343f1@box-eu8.borgbase.com:repo
Init Borgmatic ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository
Remote: Warning: Permanently added the ECDSA host key for IP address '95.217.115.47' to the list of known hosts.
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository


Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
q20343f1@box-eu8.borgbase.com:repo: Initializing repository
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Remote: q20343f1@box-eu8.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
q20343f1@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info q20343f1@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
Cannot init backup, check your Borgbase account
```

This still looks like it's an SSH file issue…

When using another name (`test2`)

```sh
docker build . -t borg-backup && docker run -v $HOME/data/to-backup/A:/storage/volA:ro -v $HOME/data/to-backup/B:/storage/volB:ro -e BORGBASE_NAME=test-2 -e BORGBASE_KEY=replaced -it borg-backup setup-new-repo
```

```
? Email address: reg+backupmaster2@kiwix.org
? Master password: [hidden]
Generate SSH key ...
Generating public/private ed25519 key pair.
Your identification has been saved in /root/.ssh/test-2_id.
Your public key has been saved in /root/.ssh/test-2_id.pub.
The key fingerprint is:
SHA256:8eMC90lAeKKi63bxC/8T185vIVO6Fo2JJ6VsGKFgQlw backup@test-2
The key's randomart image is:
+--[ED25519 256]--+
|o..E   ..        |
| o o  oo.        |
|  o ...o+        |
|  . .. . + . .   |
| . .  . S O *    |
|.  .   = @ % o   |
| . .o   = O = .  |
|.. .o. . . = .   |
|o..  oo.. . o.   |
+----[SHA256]-----+
Save key to BitWarden
c9f386a8-febd-46f4-9cb6-ac4100a8339e Kiwix Backup (reg)
To share with a organization, please enter it id (leave blank for no share):c9f386a8-febd-46f4-9cb6-ac4100a8339e
f889465c-f322-4768-9665-ac4100a833a3 Default Collection
Please enter a collection id: f889465c-f322-4768-9665-ac4100a833a3
Share key ...
Repo not exists with name test-2 , create it ...
Cannot connect to BorgBase : 'NoneType' object is not subscriptable
```

Maybe there's something wrong with my command? Let me know how to test.

**Comment by florentk** [comment]
I do not think so the name is the problem. The serveur seem very long this morning, last night it was more fast. Try with 5s for the sleep, this work for me. I suppose that the serveur had no time to init the ssh access, so I got a error whith ssh key.

My command :
`docker run  -v /home/florent/backup:/storage   -e BORGBASE_NAME=test-1   -e BW_EMAIL=florent@kaisser.name -e BW_PASSWORD=xxx -e BORGBASE_KEY=xxx  -ti backup-docker setup-new-repo`

Output : 
```
Generate SSH key ...
Generating public/private ed25519 key pair.
Your identification has been saved in /root/.ssh/test-1_id.
Your public key has been saved in /root/.ssh/test-1_id.pub.
The key fingerprint is:
SHA256:SSlxKkzRVhj1nCFZTAt4FmcHN+erzOnlRrBOtrdqKxc backup@test-1
The key's randomart image is:
+--[ED25519 256]--+
|    ooo*B*B.+ .  |
|   o  =++O.* +   |
|    o.ooo =   .  |
|     . o .  .  . |
|        S    o.  |
|           oEo.  |
|           +=+.  |
|          ..=oo  |
|           ++=o. |
+----[SHA256]-----+
Save key to BitWarden
091bba4e-118b-4b8c-844a-ac3b01447f41 LILLE.BIKE
To share with a organization, please enter it id (leave blank for no share):
Repo not exists with name test-1 , create it ...
Use repo path : y2r09s6d@box-eu8.borgbase.com:repo
Init Borgmatic ...
y2r09s6d@box-eu8.borgbase.com:repo: Initializing repository
Remote: ssh: connect to host box-eu8.borgbase.com port 22: Connection timed out
Connection closed by remote host. Is borg working on the server?
The authenticity of host 'box-eu8.borgbase.com (95.217.115.47)' can't be established.
ECDSA key fingerprint is SHA256:McOX8rDSCr2eHvhBi2Z1ogxsaF01WagS0U3r4vG1Oh0.
Are you sure you want to continue connecting (yes/no)? 
Remote: Host key verification failed.
Connection closed by remote host. Is borg working on the server?
y2r09s6d@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info y2r09s6d@box-eu8.borgbase.com:repo' returned non-zero exit status 2.
/root/.config/borgmatic/config.yaml: Error running configuration file

summary:
/root/.config/borgmatic/config.yaml: Error running configuration file
y2r09s6d@box-eu8.borgbase.com:repo: Error running actions for repository
Command 'borg init --encryption repokey --info y2r09s6d@box-eu8.borgbase.com:repo' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
Borgmatic init has failed, retry again ...
y2r09s6d@box-eu8.borgbase.com:repo: Initializing repository
The authenticity of host 'box-eu8.borgbase.com (95.217.115.47)' can't be established.
ECDSA key fingerprint is SHA256:McOX8rDSCr2eHvhBi2Z1ogxsaF01WagS0U3r4vG1Oh0.
Are you sure you want to continue connecting (yes/no)? yes
Remote: Warning: Permanently added 'box-eu8.borgbase.com,95.217.115.47' (ECDSA) to the list of known hosts.
/srv/repos/y2r09s6d/repo is not a valid repository. Check repo config.
Initializing repository at "ssh://y2r09s6d@box-eu8.borgbase.com/./repo"
Key in "<RemoteRepository ssh://y2r09s6d@box-eu8.borgbase.com/./repo>" created.
Keep this key safe. Your data will be inaccessible without it.
Remote: Storage quota: 522 B out of 2.05 GB used.
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Done.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam ssh://y2r09s6d@box-eu8.borgbase.com/./repo

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).


summary:
/root/.config/borgmatic/config.yaml: Successfully ran configuration file

```

**Comment by rgaudin** [comment]
Here's the trace for that non-existing repo

```
Repo not exists with name test-3 , create it ...
Cannot connect to BorgBase : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/init_borgbase_repository.py", line 222, in <module>
    raise e
  File "/usr/local/bin/init_borgbase_repository.py", line 217, in <module>
    DB_PORT,
  File "/usr/local/bin/init_borgbase_repository.py", line 100, in main
    repo_id = create_repo(borgbase_api_client, name)
  File "/usr/local/bin/init_borgbase_repository.py", line 75, in create_repo
    return res["data"]["repoAdd"]["repoAdded"]["id"]
TypeError: 'NoneType' object is not subscriptable
```

I was using a Create-only borgbase token so I created a Full Access one to test and I get the same results

So I printed the response and found

```py
{'data': {'repoAdd': None},
 'errors': [{'locations': [{'column': 5, 'line': 12}],
             'message': 'Over quota or too many repos.',
             'path': ['repoAdd']}]}
```

So it's because I had already two repos! Sorry about all the back and forth. I'll create an issue so to add an error check on this as it can become quite common.

The borg thing failed 4 times (with 10s sleep) before working so I guess I'll open another ticket to get that sorted.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
