### PR TITLE
add default mysqldump options 

### PR DESCRIPTION
**Pull request by florentk**
related to #59
Add "--single-transaction --quick --lock-tables=false" in mysqldump command line

### CODE REVIEW

**Comment by kelson42** [comment]
@florentk Does tha PR fix the pb? Do you plan anything else?

**Comment by florentk** [comment]
@kelson42  I couldn't reproduce the problem locally, so I have to test after the PR is validated

**Review by rgaudin — APPROVED** [review]
Looks good but we'll need to test to ensure it fixes the problem

**Comment by florentk** [comment]
I've updated the image et restart the container

**Pull request merged**
